export const cssHandles = [
  'erroCepLabel',
  'freeShippingContainer',
  'freeShippingLabel',
  'frete',
  'freteText',
  'freeShippingLabelWin',
  'freeShippingBar',
  'freeShippingBarColor',
  'freeShippingBarContainer',
  'freeShippingBarIcon',
  'freeShippingBarLine',
  'formContainer',
  'formCepEditar',
  'inputCepEditar',
  'editButton',
  'formCep',
  'inputCep',
] as const
